# This file contains values from Cookiecutter

default_context:
  project_name: "bifdraw"
  project_description: "bifdraw.py is a python gui application that helps creating bifuraction graphs"
  organization: "Department of Complex Systems, Rzeszów University of Technology"
  license: "MIT"
  minimal_python_version: 3.7
  github_name: "zszprz"
  email: "m.cmil@prz.edu.pl"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
